version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./:/usr/src/app/
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=bend-backend-task
    depends_on:
      - postgres
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bend-backend-task
    ports:
      - "5432:5432"

